language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.7
    - gcc-4.8
    - gcc-4.9
    - gcc-5

env:
  - COMPILER=gcc-4.7
  - COMPILER=gcc-4.8
  - COMPILER=gcc-4.9
  - COMPILER=gcc-5

script:
  - $COMPILER --version
  - env CC=$COMPILER cargo build --verbose
  - env CC=$COMPILER cargo test --verbose
