[package]
name = "hdrhistogram"
version = "0.1.10"
readme = "README.md"
authors = ["Jeremy Fitzhardinge <jeremy@goop.org>"]
description = "Binding to HdrHistogram_c library"
repository = "https://github.com/jsgf/rust-hdrhistogram"
documentation = "https://jsgf.github.io/hdrhistogram/"
keywords = [ "ffi", "binding", "hdrhistogram", "histogram" ]
license = "MIT"
build = "build.rs"

[dependencies]
libc = "0.1.8"

[build-dependencies]
cmake = "0.1"
